export const PROCESS_BLUEPRINT_STRING = "PROCESS_BLUEPRINT_STRING"
export const SELECT_MODE = "SELECT_MODE"
export const MODIFY_ENTITY = "MODIFY_ENTITY"
export const REMOVE_ENTITY = "REMOVE_ENTITY"
export const ROTATE_ENTITY = "ROTATE_ENTITY"
export const PLACE_ENTITY = "PLACE_ENTITY"
export const NEW_ENTITY = "NEW_ENTITY"
export const HOVER_ENTITY = "HOVER_ENTITY"
export const BATCH_UPGRADE = "BATCH_UPGRADE"
export const INCREASE_SIZE = "INCREASE_SIZE"
export const DECREASE_SIZE = "DECREASE_SIZE"



export const SELECT_ENTITY = "SELECT_ENTITY"

